### ISSUE TITLE
ImportError on cli.py

### ISSUE THREAD

**Issue by 0ssigeno** [mandiant/speakeasy#180]
Hi guys!
I tried to run the newest cli update and I encountered the following issue:
```
python3.9  speakeasy/cli.py --help
```
```  File "/home/ossigeno/Github/Dragonfly/speakeasy/speakeasy/cli.py", line 8, in <module>
    import multiprocessing as mp
  File "/usr/lib/python3.9/multiprocessing/__init__.py", line 16, in <module>
    from . import context
  File "/usr/lib/python3.9/multiprocessing/context.py", line 6, in <module>
    from . import reduction
  File "/usr/lib/python3.9/multiprocessing/reduction.py", line 15, in <module>
    import pickle
  File "/usr/lib/python3.9/pickle.py", line 33, in <module>
    from struct import pack, unpack
  File "/home/ossigeno/speakeasy/speakeasy/struct.py", line 3, in <module>
    import ctypes as ct
  File "/usr/lib/python3.9/ctypes/__init__.py", line 15, in <module>
    from struct import calcsize as _calcsize
ImportError: cannot import name 'calcsize' from partially initialized module 'struct' (most likely due to a circular import) 
```
I don't know if the issue has to do with my local python environment or what, but I don't think that having a file called `struct`, when there is already a module in the standard lib with the [same name](https://docs.python.org/3/library/struct.html) can be an issue. 

Let me know if you can reproduce the bug or I can help in anyway!

**Comment by williballenthin** [comment]
right now i'm thinking "how did this ever work?"

if you invoke speakeasy via `speakeasy` after installing with pip or setup.py then it works, but directly invoking `speakeasy/cli.py` does not. this suggests to me that everyone does the former. will this work for you @0ssigeno?

fixing this would probably involve either:
  1. renaming the `speakeasy.struct` module, which is a bit invasive, or
  2. manipulating the search path from within `speakeasy/cli.py`, which is possible, but maybe overkill

so, does this really need to be fixed, or is invoking speakeasy via the console script ok?

**Comment by jhsmith** [comment]
Great - glad that works for you. Closing this out - let us know if you encounter other issues.
