### ISSUE TITLE
log_process_event only logs external thread injection

### ISSUE THREAD

**Issue by 0ssigeno** [mandiant/speakeasy#189]
Hi guys!
I do not know if this is actually an expected behaviour or not, but [on this line ](https://github.com/mandiant/speakeasy/blob/062036ee881d412ce9e3bd214ca2a6a488606db1/speakeasy/winenv/api/usermode/kernel32.py#L1138) the event_type is set to `thread` and in the switch case inside  `log_process_event` is not present a case for that event type. The Pr is straight forward for this, just wanted to know if this is intended or not.

**Comment by williballenthin** [comment]
this is not intended (to my knowledge). lets add the case to `log_process_event`. Thanks!
