### ISSUE TITLE
Bug in read string from UNICODE_STRING and ANSI_STRING

### ISSUE THREAD

**Issue by HongThatCong** [mandiant/speakeasy#224]
LdrLoadDll and LdrGetProcedureAddress in winenv\api\usermode\ntdll.py will failed when the unicode string and ansi string which not NULL terminated.
UNICODE_STRING and ANSI_STRING don't enforce to have NULL char at end.
The len of them is the field Length in UNICODE_STRING and ANSI_STRING.

**Comment by HongThatCong** [comment]
I fixed in winenv\api\api.py
![image](https://user-images.githubusercontent.com/67528122/218350118-66f31bfd-432b-4af6-8de8-de636189c73f.png)

**Comment by HongThatCong** [comment]
And in winenv\api\usermode\ntdll.py
![image](https://user-images.githubusercontent.com/67528122/218350712-f0503f74-1fb4-4737-816d-bc9293b1f2d3.png)

**Comment by Lophiel** [comment]
Dear mentors, may I work on this issue and is there any test examples you have that essentially trigger the aforementioned issue ?

**Comment by williballenthin** [comment]
go ahead and work on the issue.

i don't have any examples offhand. @HongThatCong do you?

**Comment by HongThatCong** [comment]
ce1cdb8895c7fbda1dc1d3e8a027d0b4310e956acffa75326281670f8e2b6226
