### ISSUE TITLE
Question about stack size - alloc_stack

### ISSUE THREAD

**Issue by cecio** [mandiant/speakeasy#228]
Hello.

I was investigating an error during an emulation (unmapped memory access) and I noticed this part of code in `windows/win32.py` in `load_module`:

```
        if not self.stack_base:
            self.stack_base, stack_addr = self.alloc_stack(0x12000)
        self.set_func_args(self.stack_base, self.return_hook)
```

So, the stack is allocated to a fixed value of `0x12000`. I was wondering why, and if should not be better to allocate the `pe.OPTIONAL_HEADER.SizeOfStackReserve` instead. 

In my specific case, this fix the issue I'm experiencing in the emulation, but I was wondering if there is a reason for this.

Obviously, if you think this is useful, I can open a PR for this.

Thanks,

**Comment by williballenthin** [comment]
i'm not sure how this value was chosen. using `SizeOfStackReserve` makes sense to me, so we'd be happy to receive a PR updating this behavior.
