### ISSUE TITLE
Request to lift strong version requirement on unicorn dependency

### ISSUE THREAD

**Issue by jhhcs** [mandiant/speakeasy#243]
Speakeasy currently depends on Unicorn 1.0.2 via this line in [./requirements.txt](../blob/master/requirements.txt#L4):
```
unicorn==1.0.2
```
In practice, I have used Speakeasy without issue using more recent Unicorn versions, 2.0.1 for example does work just fine in my experience. I noticed the dependency conflict only when I tried to package both unicorn and speakeasy together for [a project of mine](https://github.com/binref/refinery/).

I was hoping that the version pin here is a little conservative and I wanted to ask whether it would be possible to make a Speakeasy release that does not have such a strict requirement. To be explicit, I have used Speakeasy successfully with unicorn version `2.0.1.post1` installed.

If the dependency requirement could be adjusted to include that version, speakeasy could be installed side by side with [angr](https://github.com/angr/angr/blob/master/pyproject.toml#L2), for example.

**Comment by williballenthin** [comment]
Hey @jhhcs, there's been a thread in #235 about this change. Would you take a peek there and leave any insight/experience you have?

As the defacto maintainer (yet not author or frequent user), I'm hesitant to make a change that might sometimes break someone's tool. Yet, at this point, Unicorn 2 is the standard version, so maybe its reasonable to get more eyes on the problem. Perhaps we could release a new major version of Speakeasy with the relaxed requirements, and existing user can pin to `speakeasy=1` if necessary?

**Comment by jhhcs** [comment]
Oh, thanks, I hadn't seen that PR. I will have a look and try to help out as best I can. You can close this as a duplicate if you want, or keep it open if you prefer to have an issue tracking it as well.

**Comment by jhhcs** [comment]
As noted in the PR, some amateur debugging and bug chasing has led me to the conclusion that Speakeasy can't be switched over to Unicorn v2 at the moment without making some (likely critical) adjustments to the Speakeasy code. I'd still prefer if that would happen at some point so it becomes compatible with Unicorn v2, but since that was not the point of this issue, I will close it out with the above conclusion. Cheers!
